require "system.clock"
require "system.brightness"
require "system.audio"
require "system.battery"
require "system.airplane"
require "system.redshift"
require "system.tablet"
require "system.headphones"
